name: Brittle Commit Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
#      - name: Install Rust and Cargo
#        uses: actions-rust-lang/setup-rust-toolchain@v1
        
#      - name: Install Clang
#        uses: egor-tensin/setup-clang@v1
      
#      - name: Install OpenCV
#        uses: Dovyski/setup-opencv-action@v1.1

      - name: Install Dependencies
        run: sudo apt install rust cargo clang opencv-dev
      
      - name: Clone Brittle
        uses: actions/checkout@v3
        
      - name: Build and Run Brittle
        run: |
          cd brittle
          cargo run
