name: Brittle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y rustc cargo clang libopencv-dev
      
      - name: Clone Brittle
        uses: actions/checkout@v3
        
      - name: Build and Run Brittle
        run: |
          cd brittle
          cargo run
